# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 563)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget {\n"
"    color: rgb(0, 0, 0); /* Change this line to set text color to black */\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid #25273d;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color:#EFEFEF;\n"
"    border: 1px solid #EFEFEF;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {    \n"
"    background-color:#EFEFEF;\n"
"}\n"
"#topLogo {\n"
"    background-color:#EFEFEF;\n"
"    background-repeat: no-repeat;\n"
"    background-position: left; /* or background-position: 0; */\n"
"    \n"
"   \n"
"}\n"
"\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"background-color:rgb(85, 170, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid rgb(40, 44, 52);\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color:#EFEFEF;\n"
"\n"
"}\n"
"#contentBottom{\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: rgb(44, 49, 58); }\n"
"#themeSettingsTopDetail { background-color:rgb(85, 170, 255);\n"
" }\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar {    background-color:#1c172e;\n"
" }\n"
"#bottomBar QLabel { font-size: 11px; color: rgb(113, 126, 149); padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#contentSettings .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#contentSettings .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"background-color:rgb(85, 170, 255);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background:rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"background:rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /* ComboBox */\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: black; /* Set font color to black */\n"
"    border-radius: 5px;\n"
"    border: 2px solid black;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/images/icons/drop-down.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat; /* Corrected typo */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: black;\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"background-color:rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"background-color:rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"QLabel{\n"
"    color: #0D0D0D;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"color:rgb(85, 170, 255);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"#pagesContainer QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(0, 0, 0, 0)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 80))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topLogo = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topLogo.sizePolicy().hasHeightForWidth())
        self.topLogo.setSizePolicy(sizePolicy)
        self.topLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topLogo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.topLogo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMinimumSize(QtCore.QSize(200, 0))
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setStyleSheet("image: url(:/images/images/images/logo (2).png);")
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo, 0, QtCore.Qt.AlignLeft)
        self.rightButtons = QtWidgets.QFrame(self.topLogo)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_6.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/mazimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon1)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_6.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_6.addWidget(self.closeAppBtn)
        self.horizontalLayout_3.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.topLogo)
        self.verticalLayout_2.addWidget(self.contentTopBg, 0, QtCore.Qt.AlignTop)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pagesContainer)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setStyleSheet("    background-color:#EFEFEF;\n"
"    border: 1px solid #EFEFEF;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.stackedWidget.addWidget(self.dashboard)
        self.timePage = QtWidgets.QWidget()
        self.timePage.setObjectName("timePage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.timePage)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.timePage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MainInputFrame = QtWidgets.QFrame(self.frame_3)
        self.MainInputFrame.setMinimumSize(QtCore.QSize(530, 0))
        self.MainInputFrame.setMaximumSize(QtCore.QSize(16777215, 350))
        self.MainInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainInputFrame.setObjectName("MainInputFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.MainInputFrame)
        self.verticalLayout_16.setContentsMargins(80, 0, 0, 0)
        self.verticalLayout_16.setSpacing(12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_4 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.txtID = QtWidgets.QLineEdit(self.frame_4)
        self.txtID.setMinimumSize(QtCore.QSize(0, 42))
        self.txtID.setStyleSheet("\n"
"#txtID {\n"
"    background-color: white;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtID:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtID.setObjectName("txtID")
        self.horizontalLayout_7.addWidget(self.txtID)
        self.verticalLayout_16.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMinimumSize(QtCore.QSize(70, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.txtWO = QtWidgets.QLineEdit(self.frame_5)
        self.txtWO.setMinimumSize(QtCore.QSize(0, 42))
        self.txtWO.setStyleSheet("\n"
"#txtWO {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtWO:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtWO.setObjectName("txtWO")
        self.horizontalLayout_8.addWidget(self.txtWO)
        self.verticalLayout_16.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.txtPT = QtWidgets.QLineEdit(self.frame_6)
        self.txtPT.setMinimumSize(QtCore.QSize(0, 42))
        self.txtPT.setStyleSheet("\n"
"#txtPT {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtPT:focus {\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtPT.setObjectName("txtPT")
        self.horizontalLayout_9.addWidget(self.txtPT)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.txtIssue = QtWidgets.QLineEdit(self.frame_7)
        self.txtIssue.setMinimumSize(QtCore.QSize(0, 42))
        self.txtIssue.setStyleSheet("\n"
"#txtIssue {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtIssue:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtIssue.setObjectName("txtIssue")
        self.horizontalLayout_10.addWidget(self.txtIssue)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.MainInputFrame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(11, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 30)
        self.verticalLayout_8.setSpacing(12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnOther = QtWidgets.QPushButton(self.frame_9)
        self.btnOther.setMinimumSize(QtCore.QSize(170, 60))
        self.btnOther.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnOther.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOther.setStyleSheet("\n"
"#btnOther{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnOther:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnOther.setAutoDefault(False)
        self.btnOther.setDefault(True)
        self.btnOther.setFlat(False)
        self.btnOther.setObjectName("btnOther")
        self.verticalLayout_8.addWidget(self.btnOther, 0, QtCore.Qt.AlignVCenter)
        self.btnPool = QtWidgets.QPushButton(self.frame_9)
        self.btnPool.setMinimumSize(QtCore.QSize(170, 60))
        self.btnPool.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnPool.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPool.setStyleSheet("\n"
"#btnPool{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnPool:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnPool.setAutoDefault(False)
        self.btnPool.setDefault(True)
        self.btnPool.setFlat(False)
        self.btnPool.setObjectName("btnPool")
        self.verticalLayout_8.addWidget(self.btnPool)
        self.verticalLayout_3.addWidget(self.frame_9, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.BottomButtonsFrame = QtWidgets.QFrame(self.timePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BottomButtonsFrame.sizePolicy().hasHeightForWidth())
        self.BottomButtonsFrame.setSizePolicy(sizePolicy)
        self.BottomButtonsFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.BottomButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomButtonsFrame.setObjectName("BottomButtonsFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.BottomButtonsFrame)
        self.horizontalLayout_11.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_11.setSpacing(12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnStart = QtWidgets.QPushButton(self.BottomButtonsFrame)
        self.btnStart.setMinimumSize(QtCore.QSize(170, 60))
        self.btnStart.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart.setStyleSheet("\n"
"#btnStart{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"#btnStart:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_11.addWidget(self.btnStart)
        self.btnPause = QtWidgets.QPushButton(self.BottomButtonsFrame)
        self.btnPause.setMinimumSize(QtCore.QSize(170, 60))
        self.btnPause.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnPause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPause.setStyleSheet("\n"
"#btnPause{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnPause:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout_11.addWidget(self.btnPause)
        self.btnFinish = QtWidgets.QPushButton(self.BottomButtonsFrame)
        self.btnFinish.setMinimumSize(QtCore.QSize(170, 60))
        self.btnFinish.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnFinish.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFinish.setStyleSheet("\n"
"#btnFinish{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnFinish:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnFinish.setObjectName("btnFinish")
        self.horizontalLayout_11.addWidget(self.btnFinish)
        self.verticalLayout.addWidget(self.BottomButtonsFrame)
        self.frame_19 = QtWidgets.QFrame(self.timePage)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.timePage)
        self.otherPage = QtWidgets.QWidget()
        self.otherPage.setObjectName("otherPage")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.otherPage)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_37 = QtWidgets.QFrame(self.otherPage)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.frame_42 = QtWidgets.QFrame(self.frame_37)
        self.frame_42.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_42.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.MainInputFrame_6 = QtWidgets.QFrame(self.frame_42)
        self.MainInputFrame_6.setMinimumSize(QtCore.QSize(530, 0))
        self.MainInputFrame_6.setMaximumSize(QtCore.QSize(16777215, 350))
        self.MainInputFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainInputFrame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainInputFrame_6.setObjectName("MainInputFrame_6")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.MainInputFrame_6)
        self.verticalLayout_34.setContentsMargins(80, 0, 0, 0)
        self.verticalLayout_34.setSpacing(12)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_45 = QtWidgets.QFrame(self.MainInputFrame_6)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_22 = QtWidgets.QLabel(self.frame_45)
        self.label_22.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_37.addWidget(self.label_22)
        self.txtID_2 = QtWidgets.QLineEdit(self.frame_45)
        self.txtID_2.setMinimumSize(QtCore.QSize(0, 42))
        self.txtID_2.setStyleSheet("\n"
"#txtID_2 {\n"
"    background-color: white;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtID_2:focus {\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"}")
        self.txtID_2.setObjectName("txtID_2")
        self.horizontalLayout_37.addWidget(self.txtID_2)
        self.verticalLayout_34.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.MainInputFrame_6)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_23 = QtWidgets.QLabel(self.frame_46)
        self.label_23.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_38.addWidget(self.label_23)
        self.cmbxWO = QtWidgets.QComboBox(self.frame_46)
        self.cmbxWO.setStyleSheet("background-color:white;\n"
"    border: 1px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"")
        self.cmbxWO.setObjectName("cmbxWO")
        self.cmbxWO.addItem("")
        self.cmbxWO.setItemText(0, "")
        self.cmbxWO.addItem("")
        self.cmbxWO.addItem("")
        self.cmbxWO.addItem("")
        self.horizontalLayout_38.addWidget(self.cmbxWO)
        self.verticalLayout_34.addWidget(self.frame_46)
        self.frame_47 = QtWidgets.QFrame(self.MainInputFrame_6)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.verticalLayout_34.addWidget(self.frame_47)
        self.frame_48 = QtWidgets.QFrame(self.MainInputFrame_6)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_34.addWidget(self.frame_48)
        self.verticalLayout_33.addWidget(self.MainInputFrame_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_36.addWidget(self.frame_42)
        self.frame_49 = QtWidgets.QFrame(self.frame_37)
        self.frame_49.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_35.setContentsMargins(11, 11, -1, -1)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_50)
        self.verticalLayout_36.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.btnBack = QtWidgets.QPushButton(self.frame_50)
        self.btnBack.setMinimumSize(QtCore.QSize(170, 60))
        self.btnBack.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBack.setStyleSheet("\n"
"#btnBack{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnBack:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnBack.setAutoDefault(False)
        self.btnBack.setDefault(True)
        self.btnBack.setFlat(False)
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout_36.addWidget(self.btnBack)
        self.verticalLayout_35.addWidget(self.frame_50)
        self.horizontalLayout_36.addWidget(self.frame_49)
        self.verticalLayout_38.addWidget(self.frame_37)
        self.BottomButtonsFrame_3 = QtWidgets.QFrame(self.otherPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BottomButtonsFrame_3.sizePolicy().hasHeightForWidth())
        self.BottomButtonsFrame_3.setSizePolicy(sizePolicy)
        self.BottomButtonsFrame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.BottomButtonsFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomButtonsFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomButtonsFrame_3.setObjectName("BottomButtonsFrame_3")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.BottomButtonsFrame_3)
        self.horizontalLayout_41.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_41.setSpacing(12)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.btnStart_2 = QtWidgets.QPushButton(self.BottomButtonsFrame_3)
        self.btnStart_2.setMinimumSize(QtCore.QSize(170, 60))
        self.btnStart_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnStart_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart_2.setStyleSheet("\n"
"#btnStart_2{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"#btnStart_2:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnStart_2.setObjectName("btnStart_2")
        self.horizontalLayout_41.addWidget(self.btnStart_2)
        self.btnPause_2 = QtWidgets.QPushButton(self.BottomButtonsFrame_3)
        self.btnPause_2.setMinimumSize(QtCore.QSize(170, 60))
        self.btnPause_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnPause_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPause_2.setStyleSheet("\n"
"#btnPause_2{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnPause_2:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnPause_2.setObjectName("btnPause_2")
        self.horizontalLayout_41.addWidget(self.btnPause_2)
        self.btnFinish_2 = QtWidgets.QPushButton(self.BottomButtonsFrame_3)
        self.btnFinish_2.setMinimumSize(QtCore.QSize(170, 60))
        self.btnFinish_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnFinish_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFinish_2.setStyleSheet("\n"
"#btnFinish_2{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnFinish_2:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnFinish_2.setObjectName("btnFinish_2")
        self.horizontalLayout_41.addWidget(self.btnFinish_2)
        self.verticalLayout_38.addWidget(self.BottomButtonsFrame_3)
        self.frame_52 = QtWidgets.QFrame(self.otherPage)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.verticalLayout_38.addWidget(self.frame_52)
        self.stackedWidget.addWidget(self.otherPage)
        self.poolPage = QtWidgets.QWidget()
        self.poolPage.setObjectName("poolPage")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.poolPage)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.frame_8 = QtWidgets.QFrame(self.poolPage)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_27 = QtWidgets.QFrame(self.frame_8)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.MainInputFrame_5 = QtWidgets.QFrame(self.frame_27)
        self.MainInputFrame_5.setMinimumSize(QtCore.QSize(530, 0))
        self.MainInputFrame_5.setMaximumSize(QtCore.QSize(16777215, 350))
        self.MainInputFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainInputFrame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainInputFrame_5.setObjectName("MainInputFrame_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.MainInputFrame_5)
        self.verticalLayout_22.setContentsMargins(80, 0, 0, 0)
        self.verticalLayout_22.setSpacing(12)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_28 = QtWidgets.QFrame(self.MainInputFrame_5)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_18 = QtWidgets.QLabel(self.frame_28)
        self.label_18.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_29.addWidget(self.label_18)
        self.txtID3 = QtWidgets.QLineEdit(self.frame_28)
        self.txtID3.setMinimumSize(QtCore.QSize(0, 42))
        self.txtID3.setStyleSheet("\n"
"#txtID3 {\n"
"    background-color: white;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtID3:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtID3.setObjectName("txtID3")
        self.horizontalLayout_29.addWidget(self.txtID3)
        self.verticalLayout_22.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.MainInputFrame_5)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_19 = QtWidgets.QLabel(self.frame_29)
        self.label_19.setMinimumSize(QtCore.QSize(70, 0))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_30.addWidget(self.label_19)
        self.txtWO3 = QtWidgets.QLineEdit(self.frame_29)
        self.txtWO3.setMinimumSize(QtCore.QSize(0, 42))
        self.txtWO3.setStyleSheet("\n"
"#txtWO3 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtWO3:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtWO3.setObjectName("txtWO3")
        self.horizontalLayout_30.addWidget(self.txtWO3)
        self.verticalLayout_22.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.MainInputFrame_5)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_20 = QtWidgets.QLabel(self.frame_30)
        self.label_20.setMinimumSize(QtCore.QSize(70, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_31.addWidget(self.label_20)
        self.txtPT3 = QtWidgets.QLineEdit(self.frame_30)
        self.txtPT3.setMinimumSize(QtCore.QSize(0, 42))
        self.txtPT3.setStyleSheet("\n"
"#txtPT3 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtPT3:focus {\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtPT3.setObjectName("txtPT3")
        self.horizontalLayout_31.addWidget(self.txtPT3)
        self.verticalLayout_22.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.MainInputFrame_5)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_21 = QtWidgets.QLabel(self.frame_31)
        self.label_21.setMinimumSize(QtCore.QSize(70, 0))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_32.addWidget(self.label_21)
        self.txtIssue3 = QtWidgets.QLineEdit(self.frame_31)
        self.txtIssue3.setMinimumSize(QtCore.QSize(0, 42))
        self.txtIssue3.setStyleSheet("\n"
"#txtIssue3 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid grey;  /* Initially, set a transparent border */\n"
"    font: bold 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"#txtIssue3:focus {\n"
"\n"
"    border: 2px solid grey;  /* Change the border color when the button is focused/clicked */\n"
"\n"
"}")
        self.txtIssue3.setObjectName("txtIssue3")
        self.horizontalLayout_32.addWidget(self.txtIssue3)
        self.verticalLayout_22.addWidget(self.frame_31)
        self.verticalLayout_21.addWidget(self.MainInputFrame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_23.addWidget(self.frame_27)
        self.BottomButtonsFrame_2 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BottomButtonsFrame_2.sizePolicy().hasHeightForWidth())
        self.BottomButtonsFrame_2.setSizePolicy(sizePolicy)
        self.BottomButtonsFrame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.BottomButtonsFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomButtonsFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomButtonsFrame_2.setObjectName("BottomButtonsFrame_2")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.BottomButtonsFrame_2)
        self.horizontalLayout_28.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_28.setSpacing(12)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btnStart3 = QtWidgets.QPushButton(self.BottomButtonsFrame_2)
        self.btnStart3.setMinimumSize(QtCore.QSize(170, 60))
        self.btnStart3.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnStart3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart3.setStyleSheet("\n"
"#btnStart3{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"}\n"
"#btnStart3:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnStart3.setObjectName("btnStart3")
        self.horizontalLayout_28.addWidget(self.btnStart3)
        self.btnPause3 = QtWidgets.QPushButton(self.BottomButtonsFrame_2)
        self.btnPause3.setMinimumSize(QtCore.QSize(170, 60))
        self.btnPause3.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnPause3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPause3.setStyleSheet("\n"
"#btnPause3{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnPause3:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnPause3.setObjectName("btnPause3")
        self.horizontalLayout_28.addWidget(self.btnPause3)
        self.btnFinish3 = QtWidgets.QPushButton(self.BottomButtonsFrame_2)
        self.btnFinish3.setMinimumSize(QtCore.QSize(170, 60))
        self.btnFinish3.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnFinish3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFinish3.setStyleSheet("\n"
"#btnFinish3{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnFinish3:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnFinish3.setObjectName("btnFinish3")
        self.horizontalLayout_28.addWidget(self.btnFinish3)
        self.verticalLayout_23.addWidget(self.BottomButtonsFrame_2)
        self.frame_25 = QtWidgets.QFrame(self.frame_8)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_23.addWidget(self.frame_25)
        self.horizontalLayout_27.addWidget(self.frame_8)
        self.frame_24 = QtWidgets.QFrame(self.poolPage)
        self.frame_24.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_24.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_62 = QtWidgets.QFrame(self.frame_24)
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.frame_62)
        self.verticalLayout_47.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.btnBack2 = QtWidgets.QPushButton(self.frame_62)
        self.btnBack2.setMinimumSize(QtCore.QSize(170, 60))
        self.btnBack2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnBack2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBack2.setStyleSheet("\n"
"#btnBack2{\n"
"\n"
"background-color:#D6D3CE;\n"
"font: bold 12pt \"Arial\";\n"
"color:black;\n"
"border-radius:0px;\n"
"border:none;\n"
"\n"
"}\n"
"#btnBack2:hover {\n"
"background-color:#D6D3CE;\n"
"}")
        self.btnBack2.setAutoDefault(False)
        self.btnBack2.setDefault(True)
        self.btnBack2.setFlat(False)
        self.btnBack2.setObjectName("btnBack2")
        self.verticalLayout_47.addWidget(self.btnBack2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_24.addWidget(self.frame_62)
        self.horizontalLayout_27.addWidget(self.frame_24)
        self.stackedWidget.addWidget(self.poolPage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.extraRightBox = QtWidgets.QFrame(self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentSettings = QtWidgets.QFrame(self.extraRightBox)
        self.contentSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentSettings.setObjectName("contentSettings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.topMenus = QtWidgets.QFrame(self.contentSettings)
        self.topMenus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenus.setObjectName("topMenus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_message = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_message.sizePolicy().hasHeightForWidth())
        self.btn_message.setSizePolicy(sizePolicy)
        self.btn_message.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_message.setFont(font)
        self.btn_message.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_message.setStyleSheet("background-image: url(:/icons/images/icons/cil-envelope-open.png);")
        self.btn_message.setObjectName("btn_message")
        self.verticalLayout_14.addWidget(self.btn_message)
        self.btn_print = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_print.sizePolicy().hasHeightForWidth())
        self.btn_print.setSizePolicy(sizePolicy)
        self.btn_print.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_print.setFont(font)
        self.btn_print.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_print.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_print.setStyleSheet("background-image: url(:/icons/images/icons/cil-print.png);")
        self.btn_print.setObjectName("btn_print")
        self.verticalLayout_14.addWidget(self.btn_print)
        self.btn_logout = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_logout.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_14.addWidget(self.btn_logout)
        self.verticalLayout_13.addWidget(self.topMenus, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.contentSettings)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleRightInfo.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label_2.setText(_translate("MainWindow", "ID:"))
        self.txtID.setPlaceholderText(_translate("MainWindow", "Enter ID"))
        self.label_3.setText(_translate("MainWindow", "WO:"))
        self.txtWO.setPlaceholderText(_translate("MainWindow", "Enter Work Order"))
        self.label_4.setText(_translate("MainWindow", "PT:"))
        self.txtPT.setPlaceholderText(_translate("MainWindow", "Enter PT"))
        self.label_5.setText(_translate("MainWindow", "Issue:"))
        self.txtIssue.setPlaceholderText(_translate("MainWindow", "Enter any Issue"))
        self.btnOther.setText(_translate("MainWindow", "OTHERS"))
        self.btnPool.setText(_translate("MainWindow", "POOL"))
        self.btnStart.setText(_translate("MainWindow", "START"))
        self.btnPause.setText(_translate("MainWindow", "PAUSE"))
        self.btnFinish.setText(_translate("MainWindow", "FINISH"))
        self.label_22.setText(_translate("MainWindow", "ID:"))
        self.txtID_2.setPlaceholderText(_translate("MainWindow", "Enter ID"))
        self.label_23.setText(_translate("MainWindow", "WO:"))
        self.cmbxWO.setItemText(1, _translate("MainWindow", "REWORK"))
        self.cmbxWO.setItemText(2, _translate("MainWindow", "CLEAN"))
        self.cmbxWO.setItemText(3, _translate("MainWindow", "PAINT"))
        self.btnBack.setText(_translate("MainWindow", "BACK"))
        self.btnStart_2.setText(_translate("MainWindow", "START"))
        self.btnPause_2.setText(_translate("MainWindow", "PAUSE"))
        self.btnFinish_2.setText(_translate("MainWindow", "FINISH"))
        self.label_18.setText(_translate("MainWindow", "ID"))
        self.txtID3.setPlaceholderText(_translate("MainWindow", "Enter ID"))
        self.label_19.setText(_translate("MainWindow", "WO:"))
        self.txtWO3.setPlaceholderText(_translate("MainWindow", "Enter Work Order"))
        self.label_20.setText(_translate("MainWindow", "PT:"))
        self.txtPT3.setPlaceholderText(_translate("MainWindow", "Enter PT"))
        self.label_21.setText(_translate("MainWindow", "Issue:"))
        self.txtIssue3.setPlaceholderText(_translate("MainWindow", "Enter any Issue"))
        self.btnStart3.setText(_translate("MainWindow", "START"))
        self.btnPause3.setText(_translate("MainWindow", "PAUSE"))
        self.btnFinish3.setText(_translate("MainWindow", "FINISH"))
        self.btnBack2.setText(_translate("MainWindow", "BACK"))
        self.btn_message.setText(_translate("MainWindow", "Message"))
        self.btn_print.setText(_translate("MainWindow", "Print"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
import resorces_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
